services:
  buzzvel-events:
    container_name: buzzvel-events
    build: .
    volumes:
      - ./buzzvel:/var/www/html/BuzzvelHolliday
    ports:
      - 8000:80
  mysql_db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: buzzvel
    ports:
      - 3306:3306
