version: "3.9"

services:
    server-nginx:
        build:
            context: ./docker/nginx/.
        depends_on:
            - php82
            - db
        container_name: server-nginx
        ports:
            - 8081:80
        volumes:
            - .:/var/www/html
        networks:
            - laravel
    php82:
        build:
            context: ./docker/php/.
        container_name: php82
        volumes:
            - .:/var/www/html
        networks:
            - laravel
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - volume-mysql:/var/lib/mysql
            - ./docker/mysql/logs:/logs
        networks:
            - laravel
    npm:
        image: node:alpine3.18
        container_name: npm
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel
networks:
    laravel:
        name: laravel
volumes:
    volume-mysql:
        name: volume-mysql

