version: '3.8'

services:
    buzzvel-events:
        container_name: buzzvel-events
        build: .
        volumes:
            - .:/var/www/html/
        ports:
            - "8000:80"
        networks:
            - buzzvel-network

    mysql_db:
        container_name: mysql_db
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: buzzvel
        ports:
            - "3306:3306"
        networks:
            - buzzvel-network

networks:
    buzzvel-network:
        driver: bridge
