version: "3.9"

services:
    server-nginx:
        build:
            context: ./docker/nginx/.
        depends_on:
            - php82
            - mysql8
        container_name: server-nginx
        ports:
            - 8081:80
        volumes:
            - .:/var/www/html
        networks:
            - laravel
    php82:
        build:
            context: ./docker/php/.
        container_name: php82
        volumes:
            - .:/var/www/html
        networks:
            - laravel
    mysql8:
        image: mysql:8.0
        container_name: mysql8
        command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=42505856 --general-log=1 --general-log-file=/logs/general-log.log
        restart: on-failure
        ports:
            - 3360:3306
        volumes:
            - volume-mysql:/var/lib/mysql
            - ./docker/mysql/logs:/logs
        environment:
            - MYSQL_DATABASE='buzzvel'
        networks:
            - laravel
    npm:
        image: node:alpine3.18
        container_name: npm
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        entrypoint: ['npm']
        networks:
            - laravel
networks:
    laravel:
        name: laravel
volumes:
    volume-mysql:
        name: volume-mysql

