version: '3.8'

services:
    buzzvel-events:
        container_name: buzzvel-events
        build: .
        volumes:
            - .:/var/www/html/
        networks:
            - buzzvel-network

    mysql_db:
        container_name: mysql_db
        image: mysql:8.0
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: buzzvel
        ports:
            - "3306:3306"
        networks:
            - buzzvel-network

    nginx:
        image: nginx:latest
        container_name: buzzvel-nginx
        restart: always
        ports:
            -   "8000:80"
        volumes:
            - ../src:/var/www
            - ./nginx:/etc/nginx/conf.d
networks:
    buzzvel-network:
        driver: bridge
